name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: pnpm/action-setup@v4      
        name: Install pnpm with the version of packageManager in package.json
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        name: Install NodeJs
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm i
      - run: pnpm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
